# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17urpjfGOoY6SMjniJU_00czaoWdUCljo
"""

import numpy as np
import time

def run_numpy_explorer():
    print("--- Syntecxhub Data Science Internship: Project 1 ---")
    print("--- NumPy Data Explorer: Sales & Performance Analyzer ---\n")

    # 1. DATA CREATION & RESHAPING [cite: 29, 31]
    # Creating a dataset representing: 4 Stores, 12 Months, 5 Product Categories
    print("[Step 1] Creating 3D Sales Dataset...")
    raw_data = np.random.randint(10, 100, size=240) # 4*12*5 = 240
    sales_cube = raw_data.reshape(4, 12, 5)
    print(f"Dataset Shape: {sales_cube.shape} (Stores, Months, Products)\n")

    # 2. INDEXING & SLICING [cite: 29]
    # Extracting sales for the first Store, first 3 Months, and all Products
    q1_store1 = sales_cube[0, 0:3, :]
    print("[Step 2] Slicing Data (Store 1, Quarter 1):")
    print(q1_store1, "\n")

    # 3. STATISTICAL & AXIS-WISE OPERATIONS
    print("[Step 3] Performing Statistical Analysis...")
    total_sales = np.sum(sales_cube)
    mean_sales = np.mean(sales_cube)

    # Axis-wise: Summing across months and products to get total per store
    # Axis 1 = Months, Axis 2 = Products
    store_performance = np.sum(sales_cube, axis=(1, 2))

    print(f"Total Units Sold: {total_sales}")
    print(f"Average Monthly Units: {mean_sales:.2f}")
    print(f"Performance per Store (Stores 1-4): {store_performance}\n")

    # 4. BROADCASTING
    # Applying a 10% 'Tax' or 'Adjustment' to every single entry without a loop
    print("[Step 4] Applying 10% Adjustment via Broadcasting...")
    adjusted_sales = sales_cube * 1.10
    print(f"Sample adjusted value (Original 1st entry): {sales_cube[0,0,0]}")
    print(f"Sample adjusted value (New 1st entry): {adjusted_sales[0,0,0]:.2f}\n")

    # 5. PERFORMANCE COMPARISON (NumPy vs Python Lists) [cite: 32]
    print("[Step 5] Performance Comparison (Summing 1 Million Items)...")
    size = 1_000_000
    py_list = list(range(size))
    np_arr = np.arange(size)

    # Time Python List
    start = time.time()
    sum(py_list)
    py_time = time.time() - start

    # Time NumPy
    start = time.time()
    np.sum(np_arr)
    np_time = time.time() - start

    print(f"Python List Time: {py_time:.5f}s")
    print(f"NumPy Array Time: {np_time:.5f}s")
    print(f"Result: NumPy is {int(py_time/np_time)}x faster!\n")

    # 6. SAVE/LOAD OPERATIONS [cite: 32]
    print("[Step 6] Saving and Loading Data...")
    np.save('sales_report.npy', sales_cube)
    loaded_data = np.load('sales_report.npy')
    print(f"Data successfully saved and reloaded. Arrays match: {np.array_equal(sales_cube, loaded_data)}")

if __name__ == "__main__":
    run_numpy_explorer()